#配置文件需要保存为utf8格式
spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: springcode-config-dev
---
spring:
  profiles: prd
  application:
    name: springcode-config-prd